### ISSUE TITLE
README info

### ISSUE THREAD

**Issue by bboe** [scalableinternetservices/crowdlib#2]
Please add the following information to the README as soon as you can.

- [ ] Project description
- [x] Link to pivotaltracker
- [x] List of team members including photo

**Comment by bboe** [comment]
Can I please get an update on this issue?

**Comment by bboe** [comment]
Can you please elaborate on the project description a little more? How might the service work, how are the communities intended to be used?

**Comment by gavrilovmiroslav** [comment]
Sure, didn't know how much detail there should be :) will do that right away.
